CompileFlags:
  Add:
    - -std=c++20
    - -I/usr/local/include

  Conditional:
    - If:
        PathMatch: ".*\\.(cu|cuh)$"
      Add:
        - -x
        - cuda
        - --cuda-gpu-arch=sm_70
        - -I/home/seal/Documents/projects/ThunderKittens/include
